[package]
name = "codeowner-gen"
version = "0.1.7-alpha.0"
authors = ["Peter Grace <pete.grace@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auditable = "0.2.0"
serde = { version = "1.0.219", features = ["derive"]}
anyhow = "1.0.98"
regex = "1.4"
lazy_static = "1.5.0"
serde_yaml = "0.9.34+deprecated"
log = "0.4.27"
env_logger = "0.8"
clap = {version = "3.2.25", features = ["suggestions", "color", "yaml"]}

[build-dependencies]
auditable-build = "0.2.0"
