#!/usr/bin/env bash
#
# Manual end-to-end test harness for codeowner-gen.
#
# For each fixture directory under e2e/, runs the tool on input.yaml and
# compares the result against expected_CODEOWNERS. The two-line "# Generated
# by ... v<ver>/<hash>" header is stripped before comparing, because the
# version and git hash vary per build.
#
# Usage:
#   ./e2e/run.sh            # run all fixtures
#   ./e2e/run.sh 04-groups  # run a single fixture by directory name
#
set -euo pipefail

# Resolve the repo root (parent of this script's directory).
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(dirname "$script_dir")"
cd "$repo_root"

echo "Building codeowner-gen..."
cargo build --quiet
bin="target/debug/codeowner-gen"

filter="${1:-}"
pass=0
fail=0

for dir in e2e/*/; do
  [ -f "${dir}input.yaml" ] || continue
  name="$(basename "$dir")"
  if [ -n "$filter" ] && [ "$name" != "$filter" ]; then
    continue
  fi

  out="$(mktemp)"
  "$bin" "${dir}input.yaml" -o "$out" >/dev/null 2>&1

  # Drop the 2-line generated header (line 1: "# Generated by ...", line 2: "#").
  actual="$(tail -n +3 "$out")"
  expected="$(cat "${dir}expected_CODEOWNERS")"
  rm -f "$out"

  if [ "$actual" == "$expected" ]; then
    echo "PASS  $name"
    pass=$((pass + 1))
  else
    echo "FAIL  $name"
    echo "----- diff (< expected | > actual) -----"
    diff <(printf '%s\n' "$expected") <(printf '%s\n' "$actual") || true
    echo "----------------------------------------"
    fail=$((fail + 1))
  fi
done

echo
echo "Results: ${pass} passed, ${fail} failed"
[ "$fail" -eq 0 ]
