#[macro_use] extern crate tracing;
mod structs;

#[cfg(test)]
mod tests;
mod cli_args;

use std::collections::HashMap;
use std::fs::{File, OpenOptions};
use clap::Parser;
use std::io::{Read, Write};
use crate::structs::{CodeOwners, Owner};
use anyhow::{Result, bail};
use tracing_subscriber::{EnvFilter, Registry, prelude::*};
use tracing_subscriber::fmt::format::FmtSpan;
use crate::cli_args::CliArgs;

static COMPRESSED_DEPENDENCY_LIST: &[u8] = auditable::inject_dependency_list!();

fn main() -> Result<()> {
    //region console logging
    let filter_layer = EnvFilter::try_from_default_env()
        .or_else(|_| EnvFilter::try_new("warn"))?;
    let format_layer = tracing_subscriber::fmt::layer()
        .event_format(
            tracing_subscriber::fmt::format()
                .with_file(true)
                .with_thread_ids(true)
                .with_thread_names(true)
                .with_line_number(true),
        )
        .with_span_events(FmtSpan::NONE);


    let subscriber = Registry::default()
        .with(filter_layer)
        .with(format_layer);
    tracing::subscriber::set_global_default(subscriber).expect("Failed to set tracing subscriber");
    //endregion

    let matches = CliArgs::parse();
    debug!(
        "codeowner-gen cargover:{} githash:{} auditable_count:{}",
        env!("CARGO_PKG_VERSION"),
        env!("GIT_HASH"),
        COMPRESSED_DEPENDENCY_LIST.len()
    );
    let filename = matches.input_file.unwrap_or("./codeowners.yaml".into());

    //region read input + process
    let mut file = File::open(filename)?;
    let mut contents = String::new();
    file.read_to_string(&mut contents)?;
    let mut code_owners = match serde_yaml::from_str::<CodeOwners>(contents.as_str()) {
        Ok(v) => v,
        Err(e) => bail!("Unable to parse config file: {:#?}", e)
    };
    let mut longest_path = 0;
    let mut grouped = false;
    // for mvp, find longest path first...
    for code_owner in &code_owners.entries {
        if code_owner.path.len() > longest_path {
            longest_path = code_owner.path.len()
        }
        match code_owner.group {
            Some(_) => { if !grouped { grouped = true; } }
            None => ()
        };
    }
    //endregion
    //region validate records, if requested
    if matches.validate {
        if let Ok(token) = std::env::var("GITHUB_TOKEN") {
            let client = reqwest::blocking::Client::new();
            let mut owners_memoized: HashMap<Owner, bool> = HashMap::new();

            let mut headers = reqwest::header::HeaderMap::new();
            headers.insert("Authorization", format!("Bearer {}", token).parse()?);
            headers.insert("Accept", "application/vnd.github.v3+json".parse()?);
            headers.insert("X-GitHub-Api-Version", "2022-11-28".parse()?);

            for code_owner in &code_owners.entries {
                for owner in code_owner.owners.iter() {
                    if let Some(memo) = owners_memoized.get(owner) {
                        if !memo {
                            warn!("Owner {} not found in GitHub API", owner);
                        }
                    } else {}
                }
            }
            } else {
            error!("GITHUB_TOKEN environment variable not set. Cannot validate records.");
        }
    }
    //endregion

    //region Sort results and write file.
    code_owners.entries.sort_by_key(|x| x.path.clone());
    if grouped {
        code_owners.entries.sort_by_key(|x| x.group.clone());
    };
    let mut fd = OpenOptions::new()
        .create(true)
        .write(true)
        .truncate(true)
        .open("CODEOWNERS")?;
    fd.write_all(format!("# Generated by https://github.com/PeterGrace/codeowner-gen v{}/{}\n#\n",
                     env!("CARGO_PKG_VERSION"),
                     env!("GIT_HASH")).as_bytes())?;
    fd.write_all("####### BEGIN UNGROUPED\n".as_bytes())?;
    let mut last_group = String::new();
    for co in code_owners.entries {
        let mut owners = String::new();
        for o in co.owners {
            owners = format!("{} {}", owners, o);
        }
        if grouped {
            if co.group.clone().is_some() {
                if last_group.is_empty() {
                    last_group = co.group.clone().unwrap();
                    fd.write_all(format!("####### BEGIN GROUP {}\n", co.group.clone().unwrap().to_ascii_uppercase()).as_bytes())?;
                }
                if co.group.clone().unwrap() != last_group
                {
                    fd.write_all(format!("### END GROUP {}\n", last_group.to_ascii_uppercase()).as_bytes())?;
                    fd.write_all(format!("####### BEGIN GROUP {}\n", co.group.clone().unwrap().to_ascii_uppercase()).as_bytes())?;
                    last_group = co.group.clone().unwrap();
                }
            }
        }
        if co.comment.is_some() {
            fd.write_all(format!("# {}\n", co.comment.unwrap()).as_bytes())?;
        };
        fd.write_all(format!("{:width$} {}\n", co.path, owners, width = longest_path).as_bytes())?;
    }
    Ok(())
    //endregion
}
