#[macro_use]
extern crate tracing;
mod owner_groups;
mod render;
mod structs;
mod teams;

mod cli_args;
#[cfg(test)]
mod tests;

use crate::cli_args::CliArgs;
use crate::structs::CodeOwners;
use anyhow::{Result, bail};
use clap::Parser;
use std::fs::{File, OpenOptions};
use std::io::{Read, Write};
use tracing_subscriber::fmt::format::FmtSpan;
use tracing_subscriber::{EnvFilter, Registry, prelude::*};

static COMPRESSED_DEPENDENCY_LIST: &[u8] = auditable::inject_dependency_list!();

fn main() -> Result<()> {
    //region console logging
    let filter_layer = EnvFilter::try_from_default_env().or_else(|_| EnvFilter::try_new("warn"))?;
    let format_layer = tracing_subscriber::fmt::layer()
        .event_format(
            tracing_subscriber::fmt::format()
                .with_file(true)
                .with_thread_ids(true)
                .with_thread_names(true)
                .with_line_number(true),
        )
        .with_span_events(FmtSpan::NONE);

    let subscriber = Registry::default().with(filter_layer).with(format_layer);
    tracing::subscriber::set_global_default(subscriber).expect("Failed to set tracing subscriber");
    //endregion

    let matches = CliArgs::parse();
    debug!(
        "codeowner-gen cargover:{} githash:{} auditable_count:{}",
        env!("CARGO_PKG_VERSION"),
        env!("GIT_HASH"),
        COMPRESSED_DEPENDENCY_LIST.len()
    );
    let filename = matches.input_file.unwrap_or("./codeowners.yaml".into());
    let mut file = File::open(filename)?;
    let mut contents = String::new();
    file.read_to_string(&mut contents)?;
    let mut code_owners = match serde_yaml::from_str::<CodeOwners>(contents.as_str()) {
        Ok(v) => v,
        Err(e) => bail!("Unable to parse config file: {:#?}", e),
    };

    // expand owner group references before merging
    let (expanded_entries, expanded_teams) = match owner_groups::expand_owner_groups(
        &code_owners.owner_groups,
        code_owners.entries,
        code_owners.teams,
    ) {
        Ok(v) => v,
        Err(err) => bail!("Invalid owner group reference: {}", err),
    };

    code_owners.entries = teams::merge_teams_into_entries(expanded_entries, expanded_teams);

    let mut longest_path = 0;
    let mut grouped = false;
    // for mvp, find longest path first...
    for code_owner in &code_owners.entries {
        // for path len, if there's a negating bang then we should account for that in our len
        // calc.
        let path_len = code_owner.path.as_os_str().len() + if code_owner.negate { 1 } else { 0 };
        if path_len > longest_path {
            longest_path = path_len;
        }
        match code_owner.group {
            Some(_) => {
                if !grouped {
                    grouped = true;
                }
            }
            None => (),
        };
    }
    if grouped {
        code_owners.entries.sort_by_key(|x| x.group.clone());
    };

    // Ensure filepaths are correctly ordered
    code_owners.entries.sort();

    // And now, to write the file.
    let mut fd = OpenOptions::new()
        .create(true)
        .write(true)
        .truncate(true)
        .open(&matches.output_file)?;
    fd.write_all(
        format!(
            "# Generated by https://github.com/PeterGrace/codeowner-gen v{}/{}\n#\n",
            env!("CARGO_PKG_VERSION"),
            env!("GIT_HASH")
        )
        .as_bytes(),
    )?;
    fd.write_all("####### BEGIN UNGROUPED\n".as_bytes())?;
    let mut last_group = String::new();
    for co in code_owners.entries {
        let mut owners = String::new();
        for o in co.owners {
            owners = format!("{} {}", owners, o);
        }
        if grouped {
            if co.group.clone().is_some() {
                if last_group.is_empty() {
                    last_group = co.group.clone().unwrap();
                    fd.write_all(
                        format!(
                            "####### BEGIN GROUP {}\n",
                            co.group.clone().unwrap().to_ascii_uppercase()
                        )
                        .as_bytes(),
                    )?;
                }
                if co.group.clone().unwrap() != last_group {
                    fd.write_all(
                        format!("### END GROUP {}\n", last_group.to_ascii_uppercase()).as_bytes(),
                    )?;
                    fd.write_all(
                        format!(
                            "####### BEGIN GROUP {}\n",
                            co.group.clone().unwrap().to_ascii_uppercase()
                        )
                        .as_bytes(),
                    )?;
                    last_group = co.group.clone().unwrap();
                }
            }
        }
        if co.comment.is_some() {
            fd.write_all(format!("# {}\n", co.comment.unwrap()).as_bytes())?;
        };
        let display_path = if co.negate {
            format!("!{}", co.path.display())
        } else {
            co.path.display().to_string()
        };
        fd.write_all(
            format!("{:width$} {}\n", display_path, owners, width = longest_path).as_bytes(),
        )?;
    }
    Ok(())
}
