name: Build

on:
  release:
    types:
      - created
    
jobs:
  generate: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Upload artifacts
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'target/${{matrix.target}}/release/codeowner-gen;target/${{matrix.target}}/release/codeowner-gen.exe'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
